[[main]]
    identifier = "appearance"
    weight=90
    [main.params]
        action = "appearance"
        icon = "sun"

[[main]]
    weight = 99
    identifier = "search"
    [main.params]
        action = "search"
        icon = "search"

[[main]]
    weight = 100
    name = "GitHub"
    url = "https://github.com/pcarlip"
    [main.params]
        icon = "github"
        showName = false
        target = "_blank"