baseURL = 'https://pcarlip.github.io/'
languageCode = 'en-us'
title = 'Peter Carlip'
theme = 'compose'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true
      title = true

[params]
  math = true