baseURL = 'https://pcarlip.pages.dev/'
languageCode = 'en-us'
title = 'Peter Carlip'
theme = 'congo'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true
      title = true

[params]
  math = true
  #author = "Peter Carlip"
  [params.header]
    logo="images/Waves_AVE.png"
    logoDark="images/Waves_AVE.png"
    showTitle=false
  [params.footer]
    showCopyright=true

[outputs]
  home = ["HTML", "RSS"]
