baseURL = 'https://pcarlip.pages.dev/'
languageCode = 'en-us'
title = 'Peter Carlip'
theme = 'hextra'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$','$']]  

[params]
  math = true
  #author = "Peter Carlip"
  enableCopyright = true
  customCSS = ["/css/images.css"]
  [params.logo]
    lightMode = "images/Waves_AVE.png"
    darkMode = "images/Waves_AVE.png" 
[outputs]
  home = ["HTML", "RSS","JSON"]

