baseURL = 'https://pcarlip.github.io/'
languageCode = 'en-us'
title = 'Peter Carlip'
theme = 'hugo-geekblog'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true
      title = true
    [markup.tableOfContents]
      startLevel = 1
      endLevel = 9


[params]
  math = true

  # Geekblog required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true


[taxonomies]
  author = "authors"
  tag = "tags"
