baseURL = "https://pcarlip.github.io/"
languageCode = "en-us"
title = "Peter Carlip"
theme = "hugo-arcana"
copyright = "© Peter Carlip. All rights reserved"


defaultContentLanguage = "en"
[languages]
    [languages.en]
        languageName = "English"
        weight = 1

[taxonomies]
    tag = "tags"

[params]
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "https://github.com/pcarlip"
